# Handling Missing Values

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Finding missing values

data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}

df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [3]:
df.isnull()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [4]:
df.isnull().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [5]:
# Removing null values

In [6]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [7]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [8]:
df.dropna(thresh= 3)
# only drop nullvalues greater than 3

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

# filling missing values

In [9]:
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [10]:
# columnwise filling of nullvalues

In [11]:
values={
    "A":100,
    "B":200,
    "C":300,
    "D":400
}

In [12]:
df.fillna(values)

       A      B      C      D
0    1.0  200.0    1.0    1.0
1    2.0    2.0    2.0  400.0
2  100.0    3.0    3.0  400.0
3    4.0    4.0  300.0  400.0
4    5.0    5.0  300.0    5.0

In [13]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0