In [1]:
import numpy as np
import pandas as pd

# Pivot tables

In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

In [4]:
df

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22

In [5]:
# melt 
melted_data=df.melt(
    id_vars=["country","year"],
    value_vars=['sales','profit'],
    var_name="melted_variables",
    value_name="values"
)

In [6]:
melted_data.pivot(
    index=['country','year'],
    columns="melted_variables",
    values='values'
)

melted_variables  profit  sales
country year
India   2020          18     90
        2021          22    110
USA     2020          20    100
        2021          25    120