# Merging joining and concatination

In [1]:
# Merging two dataframes or tables

In [2]:
import numpy as np
import pandas as pd

In [3]:
employees = pd.DataFrame(
    {
        'employee_id':[1,2,3,4,5],
        'name':['john','Anna','Peter','Linda','Bob'],
        'deparetment':['HR','IT','Finance','IT','HR']
    }
)

#Data frame 2 : Salary information
salaries=pd.DataFrame(
    {
        'employee_id':[1,2,3,6,7],
        'salary':[60000,50000,80000,55000,65000],
        'bonus':[5000,6000,7000,8000,9000]
        
    }
)

In [4]:
# employee
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   50000   6000
2            3   80000   7000
3            6   55000   8000
4            7   65000   9000

In [5]:
pd.merge(employees,salaries)

   employee_id   name deparetment  salary  bonus
0            1   john          HR   60000   5000
1            2   Anna          IT   50000   6000
2            3  Peter     Finance   80000   7000

In [6]:
pd.merge(employees,salaries, on='employee_id')

   employee_id   name deparetment  salary  bonus
0            1   john          HR   60000   5000
1            2   Anna          IT   50000   6000
2            3  Peter     Finance   80000   7000

In [7]:
# now about 'how' attribute (total 4 sub values - inner,outer,left,right) --- inner by default which maeans it will merege on the basis of leftmost part ie employye id indcies in inner side here which is upto 1-3
# ie 1,2,3
pd.merge(employees,salaries, on='employee_id', how='inner')

   employee_id   name deparetment  salary  bonus
0            1   john          HR   60000   5000
1            2   Anna          IT   50000   6000
2            3  Peter     Finance   80000   7000

In [8]:
# if we want to excute on the basis of the outer means the actual column attribute name
pd.merge(employees,salaries, on='employee_id', how='outer')

   employee_id   name deparetment   salary   bonus
0            1   john          HR  60000.0  5000.0
1            2   Anna          IT  50000.0  6000.0
2            3  Peter     Finance  80000.0  7000.0
3            4  Linda          IT      NaN     NaN
4            5    Bob          HR      NaN     NaN
5            6    NaN         NaN  55000.0  8000.0
6            7    NaN         NaN  65000.0  9000.0

In [9]:
# using left value for how attribute
pd.merge(employees,salaries, on ="employee_id", how='left')

   employee_id   name deparetment   salary   bonus
0            1   john          HR  60000.0  5000.0
1            2   Anna          IT  50000.0  6000.0
2            3  Peter     Finance  80000.0  7000.0
3            4  Linda          IT      NaN     NaN
4            5    Bob          HR      NaN     NaN

In [10]:
pd.merge(employees,salaries , on ="employee_id", how='right')
# it means it will be trated eith respect to salaries data frame

   employee_id   name deparetment  salary  bonus
0            1   john          HR   60000   5000
1            2   Anna          IT   50000   6000
2            3  Peter     Finance   80000   7000
3            6    NaN         NaN   55000   8000
4            7    NaN         NaN   65000   9000

# Concatination of 2 data frame

In [11]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [12]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [13]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [16]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [17]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [18]:
 # on the basis of rows 
pd.concat([df1,df2] , axis =1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# Joining two data fames

In [20]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [21]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [22]:
df2

   score
2     85
3     90
4     75

In [24]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [25]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [26]:
df1.join(df2, how= 'outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0