In [1]:
# Series in Pandas

# A series is a one dimensional labeled data of holding any data type ..

In [2]:

import numpy as np
import pandas as pd

In [3]:
# Creating Series

# creating via list, numpy array and dictionary

labels=['a','b','c']
my_list=[1,2,3,4]
arr= np.array([10,20,30])
d = {
    'a':10,
    'b':20,
    'c':30
}

In [4]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
dtype: int64

In [5]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [7]:
# So in case of dictionary we are having key value pairs that why we don't need any labels in case of dictioanry

# Data Frames

In [8]:
# when we combine multiple series together we will get the data frame

#Creating Data frame

In [9]:
# using dictionary
data = {
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Lucknow", "Delhi", "Mumbai"]
}

In [10]:
df = pd.DataFrame(data)

In [11]:
df

    Name  Age     City
0  Rahul   21  Lucknow
1   Aman   22    Delhi
2  Priya   20   Mumbai

#using list

In [12]:
data_list=[
    ["Satyansh Singh",21,"Lucknow"],
    ["Aman",25,"Delhi"]
]

In [13]:
# df= pd.DataFrame(data_list,lables())

# so in case of the list we dont have the headers 
# for providing the headers er can add manually

columns=["Name","Age","Place"]
df=pd.DataFrame(data_list,columns=columns)
df

             Name  Age    Place
0  Satyansh Singh   21  Lucknow
1            Aman   25    Delhi

# Selection and indexing of columns

In [14]:
data = {
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Lucknow", "Delhi", "Mumbai"],
    "Marks": [85, 90, 88],
    "Course": ["BTech", "MTech", "BCA"]
}

df = pd.DataFrame(data)
df

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech
2  Priya   20   Mumbai     88    BCA

In [15]:
df["Name"]

0    Rahul
1     Aman
2    Priya
Name: Name, dtype: object

In [16]:
df["City"]

0    Lucknow
1      Delhi
2     Mumbai
Name: City, dtype: object

In [17]:
# targetting 2 columns 

df[["Name","City"]]

    Name     City
0  Rahul  Lucknow
1   Aman    Delhi
2  Priya   Mumbai

#Creating new columns

In [18]:
df

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech
2  Priya   20   Mumbai     88    BCA

In [19]:
# if we want to add new column in existing table

df["Designation"]=["Student","Bacha","Ladka"]

In [20]:
df

    Name  Age     City  Marks Course Designation
0  Rahul   21  Lucknow     85  BTech     Student
1   Aman   22    Delhi     90  MTech       Bacha
2  Priya   20   Mumbai     88    BCA       Ladka

# Removing a column

In [21]:
df.drop("Designation", axis= 1)

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech
2  Priya   20   Mumbai     88    BCA

In [22]:
df

    Name  Age     City  Marks Course Designation
0  Rahul   21  Lucknow     85  BTech     Student
1   Aman   22    Delhi     90  MTech       Bacha
2  Priya   20   Mumbai     88    BCA       Ladka

In [23]:
df.drop("Designation", axis= 1, inplace=True)

In [24]:
df

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech
2  Priya   20   Mumbai     88    BCA

In [25]:
# if we want to drop multiple columns

In [26]:
df.drop(["Marks","Course"], axis= 1, inplace=True)

In [27]:
df

    Name  Age     City
0  Rahul   21  Lucknow
1   Aman   22    Delhi
2  Priya   20   Mumbai

In [28]:
# to drop the row

In [29]:
df.drop(0, axis = 0)

    Name  Age    City
1   Aman   22   Delhi
2  Priya   20  Mumbai

# Selecting Rows

In [30]:
data = {
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Lucknow", "Delhi", "Mumbai"],
    "Marks": [85, 90, 88],
    "Course": ["BTech", "MTech", "BCA"]
}

df = pd.DataFrame(data)
df

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech
2  Priya   20   Mumbai     88    BCA

In [31]:
df.loc[0]
# location
# depends on the lable

Name        Rahul
Age            21
City      Lucknow
Marks          85
Course      BTech
Name: 0, dtype: object

In [32]:
df.loc[[0,1]]
# location
# depends on the lable

    Name  Age     City  Marks Course
0  Rahul   21  Lucknow     85  BTech
1   Aman   22    Delhi     90  MTech

In [33]:
df.iloc[2]
# indexed location
# independent of lable in terms of location

Name       Priya
Age           20
City      Mumbai
Marks         88
Course       BCA
Name: 2, dtype: object

# Selecting subset of rows and columns

In [34]:
df.loc[[0,1]][["City","Marks"]]

      City  Marks
0  Lucknow     85
1    Delhi     90

In [35]:
df.loc[[1,2]][["Name","Age"]]

    Name  Age
1   Aman   22
2  Priya   20

# conditional selection

In [36]:
# <, >, == etc

In [37]:
df.loc[df["Age"]>21]

   Name  Age   City  Marks Course
1  Aman   22  Delhi     90  MTech

In [38]:
# for multiple conditions

In [39]:
df.loc[(df["Age"]>21) & (df["Marks"] > 85
                        )]

   Name  Age   City  Marks Course
1  Aman   22  Delhi     90  MTech